Changed the code structure of api endpoints
MLOps-KNDS/backend pull request #31
Opened 2023-04-18 00:35 UTC by pdombrza

Reworked the code structure for the model class endpoints as well as added some basic endpoints for the test model.

2023-04-18 10:59 UTC, HermanPlay requested changes
Good solution for the routers. 

We want all the routers to have there own CRUDs, which will allow to to include and use them. Try to implement them. Put cruds in a service/ folder.

2023-04-18 10:59 UTC, HermanPlay commented on api/Dockerfile
> +COPY src ./src
We changed the folder name to api. You should change also

2023-04-18 10:59 UTC, HermanPlay commented on api/Dockerfile
> +CMD uvicorn src.main:app --host $API_HOST --port $API_PORT
After changing folder name, here you should also change src to api

2023-04-18 10:59 UTC, HermanPlay commented on api/src/routers/models.py
> +from src.schemas.model import Model
Again, folder name to api

2023-04-18 10:59 UTC, HermanPlay commented on api/src/routers/models.py
> +from src.utils.utility_functions import model_db, get_model_by_id
Change src to api

2023-04-18 10:59 UTC, HermanPlay commented on api/src/schemas/model.py
> +    status: ModelStatus = ModelStatus.INACTIVE
Why did you remove the description of this field? I think it should stay

2023-04-19 00:16 UTC, pdombrza commented on api/src/schemas/model.py
> +    status: ModelStatus = ModelStatus.INACTIVE
Thanks for letting me know, I must've deleted it by accident, i readded it

2023-04-19 00:17 UTC, pdombrza commented on api/Dockerfile
> +COPY src ./src
Renamed the direcory to api

2023-04-19 21:54 UTC, HermanPlay requested changes
Your implementation is a good start. I like that you make custom responses for some errors. 

Now remove "utility_functions.py" since we already established database. Please implement your solution using SQLAlchemy and database. Also please merge latest master branch, to have the latest version of DB models.

2023-04-19 21:54 UTC, HermanPlay commented on app/Dockerfile
Please do not modify Dockerfile, try to implement solution so it works with the original Dockerfile.

2023-04-27 00:11 UTC, pdombrza commented
I implemented some basic crud for models.

2023-04-27 11:55 UTC, HermanPlay requested changes
Generally very good job, you just need to do some cleaning and organizing stuff now

2023-04-27 11:55 UTC, HermanPlay commented on app/api/main.py
> +from routers import models
Please add import together with other routers, 2 lines below

2023-04-27 11:55 UTC, HermanPlay commented on app/api/routers/models.py
> +from services import model as model_services
Check how "pool service" is imported in its router and do the same. 

You should add service into \_\_init\_\_ file.

2023-04-27 11:55 UTC, HermanPlay commented on app/api/routers/models.py
> +    models = model_services.ModelService.get_models(db=db, skip=skip, limit=limit)
If you import whole class directly, you can shorten every line containing ModelService

2023-04-27 11:55 UTC, HermanPlay commented on app/api/__init__.py
Remove this file. API should not be a module itself. It is a main app

2023-04-27 22:08 UTC, pdombrza commented on app/api/__init__.py
Oh, my bad, thanks for letting me know.

2023-04-27 22:09 UTC, pdombrza commented
I added the suggested changes

2023-04-29 10:50 UTC, TheRealSeber commented on .vscode/settings.json
> +{
first of all add ignoring .vscode files

2023-04-29 10:50 UTC, TheRealSeber commented on app/api/models/model.py
>  import enum
you can do from enum import Enum, as we did in all the others CRUD's

2023-04-29 10:50 UTC, TheRealSeber commented on app/api/routers/model.py
> +    limit: Annotated[int, Query(ge=0)] = 100,
i will just leave a comment for the rest, that will have to be implemented to all of the other routers

2023-04-29 10:50 UTC, TheRealSeber commented on app/api/routers/model.py
> +    model_id: Annotated[int, Path(title="id of model to get")],
not sure if we really have to use Annotated here to descripe what is model_id since we do it also below in the docstring @HermanPlay ?

2023-04-29 10:50 UTC, TheRealSeber commented on app/api/routers/model.py
> +    :param pool_id: pool ID
change the docstring, since it's describes pool not model

2023-04-29 10:50 UTC, TheRealSeber commented on app/api/routers/model.py
> +    new_fields: Annotated[
same as above @HermanPlay what do you think?

2023-04-29 10:50 UTC, TheRealSeber commented on app/api/routers/model.py
> +    up_model = ModelService.patch_model(db=db, model_id=model_id, model=new_fields)
I think you can just return ModelService.patch_model(db=db, model_id=model_id, model=new_fields) as in the other routers we do. you can define default status_code in the decorator

2023-04-29 10:50 UTC, TheRealSeber commented on app/api/routers/model.py
> +    return JSONResponse(status_code=201, content=model_encoded)
youu have already defined default status_code=201, so no need to write it again

2023-04-29 10:50 UTC, TheRealSeber commented on app/api/routers/model.py
> +    :param pool_id: pool ID
again make a docstring for models not pool

2023-04-29 10:50 UTC, TheRealSeber commented on app/api/schemas/model.py
> -from enum import Enum
i think you should comeback to this, it just look better

2023-04-29 10:50 UTC, TheRealSeber commented on app/api/services/model.py
> +        return JSONResponse({"detail": "model deleted"}, status_code=200)
again no need to declare status_code, since ints 200 by default

2023-04-29 10:53 UTC, TheRealSeber commented
The moment you will make the adjustments with respect to all of the comments above it should be ready to merge.

2023-04-29 13:20 UTC, pdombrza commented on app/api/schemas/model.py
> -from enum import Enum
sure

2023-04-29 14:10 UTC, TheRealSeber commented on app/api/schemas/model.py
> -from enum import Enum
as soon as you resolve all issues please mark them as resolved

2023-04-29 16:10 UTC, pdombrza commented on app/api/models/model.py
>  import enum
actually, Enum is already imported here from sqlalchemy so this would cause a name collision

2023-04-29 16:37 UTC, matined approved these changes

2023-04-29 16:44 UTC, TheRealSeber commented
Ready to merge

2023-04-29 18:21 UTC, merged