Routers development for the API
MLOps-KNDS/backend pull request #38
Opened 2023-04-19 14:58 UTC by TheRealSeber

Need a schemes fix to work.

2023-04-19 21:47 UTC, HermanPlay requested changes
You haven't implemented methods to update user records. Please do so.

2023-04-19 21:47 UTC, HermanPlay commented on app/api/schemas/user.py
> +#  creates possibility to do for example:  if "onwer" in Role
You have a typo here "onwer"

2023-04-20 17:13 UTC, HermanPlay approved these changes

2023-04-20 17:33 UTC, HermanPlay commented on app/requirements.txt
> +email-validator==2.0.0
Please add this requirement to a global requirements, required for auto-documentation

2023-04-21 13:25 UTC, matined approved these changes

2023-04-21 14:20 UTC, merged