Class ModelDeployment
MLOps-KNDS/backend pull request #43
Opened 2023-04-23 16:13 UTC by HermanPlay

2023-04-23 20:48 UTC, matined requested changes
great job, two additional things:
1. Could you also add a static method that allows to delete an existing model deployment?
2. k8s folder can be removed from here, I'll pass it to devops team, so they can recreate the setup in deployment pipeline

2023-04-23 20:48 UTC, matined commented on app/api/utils/model_deployment.py
> +
don't put an empty line at the beginning of a method

2023-04-23 20:48 UTC, matined commented on app/api/utils/model_deployment.py
> +    def deploy(self):
add return types everywhere

2023-04-24 11:40 UTC, HermanPlay commented
@matined Done

2023-04-24 17:05 UTC, matined approved these changes

2023-04-25 21:08 UTC, matined approved these changes

2023-04-25 21:13 UTC, merged