Feature/crud for gates
MLOps-KNDS/backend pull request #44
Opened 2023-04-26 22:45 UTC by lukassw1

model, crud, router for gate added

2023-04-27 12:07 UTC, HermanPlay requested changes
Good solution, just need to clean up a bit

2023-04-27 12:07 UTC, HermanPlay commented on app/api/models/gate.py
> +    gate_id = Column(Integer, ForeignKey("gate.id"), primary_key=True)
We want only id to be primary key

2023-04-27 12:07 UTC, HermanPlay commented on app/api/models/gate.py
> +    gate_id = Column(Integer, ForeignKey("gate.id"), primary_key=True)
Same as above

2023-04-27 12:07 UTC, HermanPlay commented on app/api/schemas/gate.py
> +class GatePostAddUser(BaseModel):
I think you forgot to add also user id, so we know which user to add

2023-04-27 12:40 UTC, lukassw1 commented on app/api/models/gate.py
> +    gate_id = Column(Integer, ForeignKey("gate.id"), primary_key=True)
good idea, should i change also other models? They have same mistake i think

2023-04-27 12:50 UTC, lukassw1 commented on app/api/services/gate.py
> +    def get_gate_by_name(cls, db: Session, name: str) -> gate_models.Gate | None:
It depends if we want to have gates with the same name. Because if don't, we can check the name and raise an error eventually

2023-04-27 14:24 UTC, HermanPlay commented on app/api/models/gate.py
> +    gate_id = Column(Integer, ForeignKey("gate.id"), primary_key=True)
@matined

2023-04-27 17:44 UTC, matined commented on app/api/models/gate.py
> +    gate_id = Column(Integer, ForeignKey("gate.id"), primary_key=True)
yes, please, I'd prefer to use artificial primary key (id) as it's convenient for frontend implementation

2023-04-27 17:44 UTC, matined commented on app/api/models/gate.py
> +    gate_id = Column(Integer, ForeignKey("gate.id"), primary_key=True)
we can set gate_id and other fields like that to unique if it's possible

2023-04-27 18:03 UTC, matined requested changes

2023-04-27 18:03 UTC, matined commented on app/api/services/gate.py
> +from datetime import datetime
import external modules before internal ones

2023-04-27 18:03 UTC, matined commented on app/api/services/gate.py
> +    def get_gate_by_name(cls, db: Session, name: str) -> gate_models.Gate | None:
I agree that we need this method

2023-04-27 18:03 UTC, matined commented on app/api/services/gate.py
> +    def patch_gate(
patching will need a check if new new names doesn't already exist

2023-04-29 16:34 UTC, matined approved these changes

2023-04-29 22:29 UTC, matined approved these changes

2023-04-29 22:29 UTC, merged