Added tests for the user router
MLOps-KNDS/backend pull request #45
Opened 2023-04-27 18:19 UTC by TheRealSeber

2023-04-27 21:29 UTC, matined requested changes
this comments apply to all the tests

2023-04-27 21:29 UTC, matined commented on app/api/tests/test_user.py
> +    assert response.status_code == 200
again, do not test two functionalities in one unit test

2023-04-27 21:29 UTC, matined commented on app/api/tests/test_user.py
> +    assert response.status_code == 200
put all asserts together at the end of a test and leave an empty line before them

2023-04-27 21:29 UTC, matined commented on app/api/tests/test_user.py
> +        "surname": "test_patch_surname",
put excepted data before assert and at the put just

assert response.status_code == expected_status_code
assert data == expected_data

2023-04-29 16:29 UTC, matined approved these changes

2023-04-29 16:29 UTC, matined commented on .flake8
> +extend-ignore = E203
why do we add E203

2023-04-29 17:17 UTC, TheRealSeber commented on .flake8
> +extend-ignore = E203
It has already been there, for some reason adding  two new lines marked it as if it was deleted and then added again

2023-04-29 17:19 UTC, matined commented on .flake8
> +extend-ignore = E203
ok

2023-04-29 18:57 UTC, merged