Create a unit-test job in CI.yaml
MLOps-KNDS/backend pull request #51
Opened 2023-05-03 08:14 UTC by KubaKrzych

Added a job that tests the code.

2023-05-07 11:21 UTC, KubaKrzych commented
@matined @TheRealSeber 
The CI pipeline runs just fine. I've decided to add caching the dependencies, but I've not found it very useful, as the process of collecting them does not take that much time, but installing them is what takes the longest.

2023-05-08 11:46 UTC, matined requested changes

2023-05-08 11:46 UTC, matined commented on .github/workflows/CI.yaml
> +          pip install -r requirements.txt pytest httpx
add pytest and httpx to requirements.txt

2023-05-08 11:46 UTC, matined commented on .github/workflows/CI.yaml
> +          pytest
can we add `-vv` flags?

2023-05-08 11:46 UTC, matined commented on .github/workflows/CI.yaml
> +
Additionally to checking if tests pass we want to check and report code coverage. We can use `pytest-cov` for calculating and generating a html report. Let's also check if github workflows offers a possibility to publish the report.

2023-05-08 19:26 UTC, KubaKrzych commented on .github/workflows/CI.yaml
> +
I've found an interesting GitHub action that writes a comment whenever a pull_request is made. You can see an example below.

2023-05-08 19:28 UTC, KubaKrzych commented
@matined Could I ask you for the review of the changes I've made? I've implemented everything you had listed, but I'm not sure whether I did so in a way you've wanted.

2023-05-08 19:30 UTC, matined commented on .github/workflows/CI.yaml
> +
Yeah, that's what we want. However, we still cannot check which lines are covered, right?

2023-05-08 20:01 UTC, matined reviewed
Great! Can we check if we can somehow see which lines are covered?

2023-05-10 15:08 UTC, KubaKrzych commented
> Great! Can we check if we can somehow see which lines are covered?

I see what you were referring to. I've added the report of uncovered lines in tests.

2023-05-10 15:54 UTC, merged