Feature/db tests fix
MLOps-KNDS/backend pull request #53
Opened 2023-05-05 09:28 UTC by TheRealSeber

Now every time the test is started, the database will be created. it's very inefficient and we should find the way to start it only once, but it is what it is for now

2023-05-05 10:21 UTC, matined submitted a review, later dismissed

2023-05-05 10:26 UTC, matined commented
@KubaKrzych it should solve your problems with CI pipeline ;)

2023-05-05 18:42 UTC, matined requested changes

2023-05-05 18:44 UTC, KubaKrzych commented
Well, whenever I set up a db with _docker-compose up database_ as a process, and run a _pytest_ command I still get the same error that the schema "core" doesn't exist.

If we only want to test the db, I'm pretty sure I should be able to test the db without creating the containerised api application. @TheRealSeber , to make sure everything works as is supposed to, you can test it locally by running:

1. _docker-compose up database_
2. pytest

There should be no errors after running these two commands. If there are any, it means that something still needs to be done.

2023-05-06 10:27 UTC, TheRealSeber commented on app/api/tests/conftest.py
> +    models.Base.metadata.drop_all(bind=engine)
> @TheRealSeber we miss creating 'core' shema if not exists

no, in the models module there is a code

```
metadata_obj = MetaData(schema="core")
```

which as i know adds metadata data creates schema core. moreove i was testing it locally and it worked, both yesterday and now

2023-05-06 10:54 UTC, matined commented on app/api/tests/conftest.py
> +    models.Base.metadata.drop_all(bind=engine)
it doesnt work locally, do you remove the old database container when testing? Backend creates the schema using this piece of code: 
![image](https://user-images.githubusercontent.com/30211831/236619943-3f687ee5-4053-44ba-8c4b-f059f8557c0e.png)

I think we miss it it tests/ folder

2023-05-07 10:50 UTC, TheRealSeber commented on app/api/tests/conftest.py
> +    models.Base.metadata.drop_all(bind=engine)
added

2023-05-07 15:53 UTC, matined approved these changes

2023-05-08 10:50 UTC, merged