Model details, ORM models, schemas, endpoints
MLOps-KNDS/backend pull request #61
Opened 2023-05-15 21:41 UTC by HermanPlay

For now endpoints are implemented the same way as we implemented every other one. 

For example, now to remove model_details, we have to go to path /model/{id}/details/{model_details_id}
Which in my opinion is redundant. As i understand every model can have only one model_details record associated with it. So i think we can reduce amount of id's in the path and get id of model details from model table.

2023-05-15 22:46 UTC, matined approved these changes

2023-05-15 22:46 UTC, matined commented on app/api/models/model_details.py
> +    artifact_uri = Column(String(255), nullable=False)
all the fields beside ids are rather nullable, we can register a model withput specifing cpu, memory itp

2023-05-15 22:46 UTC, matined commented on app/api/routers/model.py
> +router.include_router(model_details_router, prefix="/{model_id}/details")
is there a reason to put prefix here instead of in the construction?

2023-05-15 22:46 UTC, matined commented on app/api/routers/model_details.py
> +@router.get("/", response_model=list[ModelDetails], status_code=200, deprecated=True)
we dont want this endpoint, we dont need to list all model details

2023-05-15 22:46 UTC, matined commented on app/api/routers/model_details.py
> +@router.get("/{model_details_id}", response_model=ModelDetails, status_code=200)
I'd prefer to get details only by model_id

2023-05-15 22:46 UTC, matined commented on app/api/schemas/model_details.py
> +    pass
it a debris, right?

2023-05-15 22:50 UTC, matined requested changes

2023-05-15 22:50 UTC, matined commented on app/api/routers/model_details.py
> +router = APIRouter(tags=["model_details"])
let's use '-' instead of '_' in tags

2023-05-16 12:27 UTC, HermanPlay commented on app/api/schemas/model_details.py
> +    pass
I was thinking that we cannot modify model_id, and we can only specify it when we add model_details. If I am thinking wrong we can make a possibility to modify model_id

2023-05-16 12:36 UTC, matined commented on app/api/schemas/model_details.py
> +    pass
My comment was about "pass", but let me describe the general idea which is that every time a new model is created a new record is inserted into model_details and it's a one-to-one relationship. By default all values beside model_id are nulls, but you have to insert them before deploying a model.

2023-05-16 14:03 UTC, matined requested changes
I'm sorry, but I still need some changes:

1. I don't want to pass model_details_id while calling endpoints, only model_id
2. I don't want to expose PUT and DELETE 

So, finally, We want to expose two endpoints:
- GET /model/{model_id}/details
- PATCH /model/{model_id}/details

put and delete should be performed when PUT /model and DELETE /model/{model_id} are called

2023-05-16 16:02 UTC, matined approved these changes

2023-05-16 16:38 UTC, matined commented
> Maybe now it works :)

Great job!

2023-05-16 16:39 UTC, matined approved these changes

2023-05-16 20:18 UTC, merged