Feature/istio utils
MLOps-KNDS/backend pull request #63
Opened 2023-05-17 13:11 UTC by TheRealSeber

Branch for developing the istio utils

2023-05-18 22:10 UTC, matined requested changes

2023-05-18 22:10 UTC, matined commented on app/api/utils/virtual_service.py
> +class VirtualService:
Rename to PoolDeployment

2023-05-18 22:10 UTC, matined commented on app/api/utils/istio_manifest_generator.py
> +class IstioManifestGen:
Rename to IstioVirtualServiceGenerator and modify structure:
1. Add constructor that takes name and models' names
2. Rename generate_vs_manifest to generate() without any parameters

It will be easier to extend later

2023-05-18 22:10 UTC, matined commented on app/api/utils/constants.py
> +    GROUP = "networking.istio.io"
let's add a prefix like 'ISTIO_VS_'

2023-05-18 22:10 UTC, matined commented on app/api/utils/istio_manifest_generator.py
> +                                    "host": f"{model.name}",
just put model.name instead of f"{model.name}"

2023-05-18 22:10 UTC, matined commented on app/api/utils/istio_manifest_generator.py
> +                                    "port": {"number": 80},
magic number, use Constants.K8S_SERVICE_PORT

2023-05-18 22:40 UTC, HermanPlay requested changes
You should attend your English classes more, bro

2023-05-18 22:40 UTC, HermanPlay commented on app/api/tests/test_user.py
> +    expected_responce = {
bro, response should be spelled with s, not c. fix the typo pls

2023-05-18 22:40 UTC, HermanPlay commented on app/api/tests/test_user.py
> +    assert response.json() == expected_responce
Same as above

2023-05-19 16:02 UTC, matined commented on app/api/utils/pool_deployment.py
> +    def __init__(self, models: list[model_schemas.Model], pool_name: str) -> None:
We want to pass objects from 'pool_model' table instead of 'model'

2023-05-30 13:40 UTC, TheRealSeber commented
> what a trash pr

i am devops here fuck off bro

2023-05-30 13:43 UTC, closed without merging