Feature/pool model endpoints
MLOps-KNDS/backend pull request #67
Opened 2023-05-20 14:28 UTC by TheRealSeber

2023-05-20 14:31 UTC, TheRealSeber commented
idk how to get a data from the relationship using the sqlalchemy

and i am mad af.

2023-05-21 20:50 UTC, matined commented
> idk how to get a data from the relationship using the sqlalchemy
> 
> and i am mad af.

Let's return only model_id, we'll add name as a separate task as it's harder and we'll have to do it in a few places

2023-05-22 14:38 UTC, matined requested changes

2023-05-22 14:38 UTC, matined commented on app/api/tests/test_config/__init__.py
dont we already have `/tests/config` and `tests/db` folders? Is it a mistake?

2023-05-22 17:33 UTC, matined approved these changes

2023-05-24 09:24 UTC, TheRealSeber commented
Nabijanie commitow na profilu >>>>

2023-05-24 09:24 UTC, merged