Prototype of authentication for users
MLOps-KNDS/backend pull request #68
Opened 2023-05-22 12:13 UTC by HermanPlay

To test it, you need .env file with credentials. Text me if you want me to send it to you.

2023-05-22 14:29 UTC, matined requested changes

2023-05-22 14:29 UTC, matined commented on app/api/main.py
> +config = Config("config.env")  # read config from .env file
can it read from env vars instead of .env file? Maybe it already does it?

2023-05-22 14:29 UTC, matined commented on app/api/main.py
> +app.add_middleware(SessionMiddleware, secret_key="secret-string")
does the "secret-string" name refer to something?

2023-05-22 14:29 UTC, matined commented on app/api/main.py
> +async def me(user=Depends(get_current_user)):
can we move all the endpoints related to authentication and authorization to their own router?

2023-05-22 14:29 UTC, matined commented on app/api/main.py
> +class UserValidationMiddleware(BaseHTTPMiddleware):
let's move this class to some other file

2023-05-22 15:17 UTC, HermanPlay commented on app/api/main.py
> +config = Config("config.env")  # read config from .env file
We can add those settings to Settings class, which indeed can read from env vars

2023-05-22 15:20 UTC, HermanPlay commented on app/api/main.py
> +app.add_middleware(SessionMiddleware, secret_key="secret-string")
Basically its a key to cypher our sessions, according to official [documentation](https://www.starlette.io/middleware/#sessionmiddleware) this key should be a random string.

2023-05-24 08:36 UTC, HermanPlay commented
@matined pls review

2023-06-05 19:13 UTC, HermanPlay commented
> review ongoing, please be patient mr.f

Thank you Mr S

2023-06-12 12:05 UTC, TheRealSeber commented
please mr.f be patient more. some day mr nędzi will find some time for you.

2023-06-13 14:55 UTC, matined requested changes

2023-06-13 14:55 UTC, matined commented on app/api/routers/protected.py
> +from fastapi import APIRouter, Depends
Let's remove this router, protect all other routers instead and we can merge the PR ;))

2023-06-20 17:03 UTC, matined commented
Is it something new? Let me know when I can try it out :))

2023-06-20 17:08 UTC, HermanPlay commented
> Is it something new? Let me know when I can try it out :))

You can already. Now after logging in you get bearer token which you can use even to access api from terminal. 

In bearer you have user id encoded with expiration time.

It also adds user to database if user doesn't exist.

2023-06-21 16:36 UTC, matined approved these changes

2023-06-21 16:38 UTC, merged