Moved pingers to seperate file
MLOps-KNDS/backend pull request #85
Opened 2023-07-05 21:25 UTC by HermanPlay

2023-07-06 12:29 UTC, matined requested changes
The code from DeploymentPinger is still duplicated in ServicePinger ;) What about a generic function that takes an object and a method like `read_namespaced_deployment_status` as a argument?

2023-07-09 15:24 UTC, matined requested changes

2023-07-09 15:24 UTC, matined commented on app/api/utils/cluster_pingers.py
> +    Pings services in a given namespace using kubernetes api.
There is 'service' in all the docstrings, it it correct?

2023-07-09 15:24 UTC, matined commented on app/api/utils/cluster_pingers.py
> +    def __init__(
This set of parameters makes the method not really generic, I'd remove name and namespace and put:

ping_callback: Callable
ping_callback_args: list | dict
ping_predicate: Callable
error_callback: Callable
error_callback_args: list | dict
ping_limit: int

2023-07-09 15:24 UTC, matined commented on app/api/utils/cluster_pingers.py
> +        config.load_incluster_config()
Already in constructor

2023-07-09 22:16 UTC, HermanPlay commented on app/api/utils/cluster_pingers.py
> +    Pings services in a given namespace using kubernetes api.
Yes, but i don't mean kubernetes [service](https://kubernetes.io/docs/concepts/services-networking/service/), rather i mean anything which is in the cluster, deployment, pod, role, etc.

2023-07-09 22:16 UTC, HermanPlay commented on app/api/utils/cluster_pingers.py
> +        config.load_incluster_config()
Done

2023-07-09 22:19 UTC, matined commented on app/api/utils/cluster_pingers.py
> +    Pings services in a given namespace using kubernetes api.
can we use 'resource' not to mislead?

2023-07-10 11:21 UTC, matined approved these changes

2023-07-10 11:22 UTC, matined commented
Good job, let's merge it, we'll fix bugs if there are ones later ;)

2023-07-10 14:59 UTC, merged